# Generated by Django 4.2.9 on 2024-02-01 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Joylashuv latitude')),
                ('longitude', models.FloatField(verbose_name='Joylashuv longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateField()),
                ('meals', models.ManyToManyField(related_name='orders', to='products.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
            ],
        ),
    ]
