# Generated by Django 4.2.9 on 2024-02-02 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_alter_order_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='order',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Umumiy to'lov(chek)"),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Umumiy to'lov")),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.meal', verbose_name='Taom')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='orders.orderitem', verbose_name='Items'),
        ),
    ]
