# Generated by Django 4.2.9 on 2024-02-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_meals_order_total_payment_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Umumiy to'lov"),
        ),
    ]
